name: Build AndroidAPS APK
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-APK
          path: app/build/outputs/apk/debug/app-debug.apk
      - name: Upload Full Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AndroidAPS-Full-APK
          path: app/build/outputs/apk/full/debug/app-full-debug.apk


      - name: List build output
        run: ls -R app/build/outputs/

