name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Generate Keystore
      run: |
        keytool -genkeypair -v \
          -keystore android-auto-key.keystore \
          -alias key \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -dname "CN=Android, OU=Mobile, O=Company, L=City, ST=State, C=US" \
          -storepass "01093030445aA" \
          -keypass "01093030445aA"

    - name: Base64 Encode Keystore (Optional)
      run: |
        base64 android-auto-key.keystore > android-auto-key.keystore.b64

    - name: Build release APK
      run: ./gradlew app:assembleFullRelease

    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOL_VERSION
        
    - name: Sign App
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/full/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: 'key'
        keyStorePassword: '01093030445aA'
        keyPassword: '01093030445aA'
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

    - name: Align APK
      run: |
        $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/zipalign -v 4 \
          app/build/outputs/apk/full/release/app-full-release-unsigned.apk \
          app/build/outputs/apk/full/release/app-full-release.apk

    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: APK release generated
        path: app/build/outputs/apk/full/release

