name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Build release APK
      run: ./gradlew app:assembleFullRelease

    - name: Setup build tool version variable
      shell: bash
      run: |
        BUILD_TOOLS_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
        echo "BUILD_TOOLS_VERSION=$BUILD_TOOLS_VERSION" >> $GITHUB_ENV
        echo Last build tool version is: $BUILD_TOOLS_VERSION

    - name: Sign App
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/full/release
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: 'key'
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOLS_VERSION }}

    - name: Align APK
      run: |
        $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/zipalign -v 4 \
          app/build/outputs/apk/full/release/app-full-release-unsigned.apk \
          app/build/outputs/apk/full/release/app-full-release-aligned.apk

    - name: Sign APK using apksigner
      run: |
        $ANDROID_HOME/build-tools/$BUILD_TOOLS_VERSION/apksigner sign --ks /tmp/keystore.jks \
          --ks-key-alias key --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} \
          --key-pass pass:${{ secrets.KEY_PASSWORD }} \
          --out app/build/outputs/apk/full/release/app-full-release-signed.apk \
          app/build/outputs/apk/full/release/app-full-release-aligned.apk

    - name: Upload APK Release
      uses: actions/upload-artifact@v4
      with:
        name: APK release generated
        path: app/build/outputs/apk/full/release/app-full-release-signed.apk
